# SWE-agent Configuration Override
# Minimal configuration - only override model settings
# SWE-agent has strict schema validation, so only basic model config is allowed

agent:
  model:
    name: "anthropic/claude-sonnet-4-5"
    api_base: "https://claude.nnppn.cn/api"
    per_instance_cost_limit: 2
#    per_instance_call_limit: 20
    # max_tokens: 4096
  history_processors:
    - type: last_n_observations
      n: 5
    - type: cache_control
      last_n_messages: 2

# Note: Other settings like cost_limits, max_iterations, tools, etc.
# should be set via command line arguments or use default config
# Example: --agent.model.per_instance_cost_limit=2.00
env:
  deployment:
    python_standalone_dir: ""