# SWE-agent Configuration Override
# Minimal configuration - only override model settings
# All other settings use defaults from config/default.yaml

agent:
  model:
    name: "anthropic/claude-sonnet-4-5"
    api_base: "https://claude.nnppn.cn/api"
actions:
  open_pr: true
  pr_config:
    base: main
    branch_prefix: swe-agent/
env:
  # repo:
    # github_url: https://github.com/SWE-agent/test-repo
  deployment:
    # image: tiny
    python_standalone_dir: ""
# problem_statement:
#   github_url:
#     https://github.com/SWE-agent/test-repo/issues/1
