# SWE-agent Configuration Override
# Minimal configuration - only override model settings
# All other settings use defaults from config/default.yaml

agent:
  model:
    name: "anthropic/claude-sonnet-4-5"
    api_base: "https://claude.nnppn.cn/api"
