# SWE-agent Configuration Override
# Based on: https://github.com/SWE-agent/SWE-agent/blob/main/config/demo/default.yaml
# This file overrides only the model configuration

agent:
  model:
    # 尝试不同的模型名称格式
    name: "anthropic/claude-sonnet-4-5"  # 或尝试 "claude-sonnet-4-5" 
    # API base - litellm 会自动添加 /v1，所以这里不应该包含 /v1
    api_base: "https://claude.nnppn.cn/api"
    # 如果上面的不行，可以尝试：
    # api_base: "https://claude.nnppn.cn"
    # 或者检查代理服务器期望的格式

