# SWE-agent Configuration
# Minimal override configuration - uses default config from SWE-agent
# Only override necessary settings

# Model configuration
agent:
  model:
    name: "claude-sonnet-4.5"
    api_base: "https://claude.nnppn.cn/api"

