# SWE-agent Configuration Override
# Based on: https://github.com/SWE-agent/SWE-agent/blob/main/config/demo/default.yaml
# This file overrides only the model configuration

agent:
  model:
    name: "anthropic/claude-sonnet-4.5"
    api_base: "https://claude.nnppn.cn/api"
    # Note: parse_function and max_input_token will be auto-detected/handled by SWE-agent

