server:
  port: 8080
  host: localhost

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: notex

email:
  host: smtp.gmail.com
  port: 587
  username: your-email@gmail.com
  password: your-app-password
  from_email: your-email@gmail.com
  from_name: Notex System
  use_tls: true
  templates_dir: templates/email
  locales_dir: locales

jwt:
  secret_key: your-secret-key-change-this-in-production
  access_token_expiry: 24
  refresh_token_expiry: 168

rate_limit:
  ip:
    rate: 100
    burst: 200
    ttl: 3600s
  api:
    rate: 1000
    burst: 2000
    ttl: 3600s
  login:
    rate: 5
    burst: 10
    ttl: 3600s

file_storage:
  upload_dir: uploads
  allowed_types:
    - image/jpeg
    - image/png
    - image/gif
    - image/webp
  max_size: 10485760
  url_prefix: /uploads/
  thumbnail_size: 300 