# Server 配置
server:
  port: 8080
  host: localhost

# 数据库配置
database:
  host: localhost
  port: 5432
  user: postgres
  password: ""  # 建议使用环境变量设置
  dbname: notex

# 邮件配置
email:
  host: smtp.gmail.com
  port: 587
  username: your-email@gmail.com  # 建议使用环境变量设置
  password: your-app-password     # 建议使用环境变量设置
  from_email: your-email@gmail.com
  from_name: Notex System
  use_tls: true
  templates_dir: templates/email
  locales_dir: locales

# JWT配置
jwt:
  secret_key: your-secret-key  # 建议使用环境变量设置
  access_token_expiry: 24    # 访问令牌有效期（小时）
  refresh_token_expiry: 168  # 刷新令牌有效期（小时）

# 限流配置
rate_limit:
  # IP限流配置
  ip:
    rate: 100    # 每秒请求数
    burst: 200   # 令牌桶容量
    ttl: 3600s   # 限流器生存时间
  # API限流配置
  api:
    rate: 1000   # 每秒请求数
    burst: 2000  # 令牌桶容量
    ttl: 3600s   # 限流器生存时间
  # 登录限流配置
  login:
    rate: 5      # 每秒请求数
    burst: 10    # 令牌桶容量
    ttl: 3600s   # 限流器生存时间 